version: "3.7"
services:

  app:
      build:
        args:
          user: yogapermana
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: my-blog
      container_name: my-blog
      # restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ../:/var/www:delegated
      networks:
        - blog

  nginx:
      image: nginx:1.17-alpine
      container_name: blog-nginx2
      # restart: unless-stopped
      ports:
        - 80:80
      volumes:
        - ../:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - blog
      working_dir: /var/www/

networks:
  blog:
    driver: bridge